apiVersion: v1
kind: Pod
metadata: 
  name: kuard2
  labels:
    env: prod
    app: kuard
    ver: v1
spec: 
  containers:
  - image: us-central1-docker.pkg.dev/civil-orb-388902/goserver/kuard:blue
    name: kuard
    ports: 
    - containerPort: 8080
      name: http
      protocol: TCP
    volumeMounts:
    - name: init-sql
      mountPath: /config
      readOnly: true
  volumes:
  - name: init-sql
    configMap:
      name: init-sql
